### ISSUE TITLE
Why Fitness trait can't be just f64?

### ISSUE THREAD

**Issue by greyblake** [m-decoster/RsGenetic#22]
Hi!
Thanks for the nice library!

I'd like to get some clarification about `Fitness` abstraction. What it exists for, and why it can not be just `f64`? (So Phenotype's `fitness` function returns only `f64`). The smaller(greater) returned fitness, the better are parameters.

I guess there are some ideas behind `Fitness`, that  I could not get.

Another question: Does the algorithm finds the smallest fitness or the biggest one?

Thanks in advance!

P.S. Please consider adding this info to README, maybe I'm not the one who's confused :)

**Comment by m-decoster** [comment]
The `Fitness` abstraction exists to allow users to define what should be optimised. It also allows to simply use `f64` if you implement `Fitness` for a struct containing `f64` (though I admit, this is a bit of a hassle).

One use case is if you want to optimise two fitness variables at once, perhaps in a weighted sum, but you also want to be able to see during or after the optimisation what the values of these two fitness variables are. Consider the following pseudocode example:

```
struct MyFitness {
    f1: f64,
    f2: f64,
}

// ...
fn fitness(&self) -> MyFitness {
    a * f1 + (1 - a) * f2
}
```

If only `f64` is allowed, this weighted sum can still be used as the fitness, but you won't be able to extract `f1` and `f2` as easily.

Regarding your second question: it should find the largest fitness. If it doesn't, that's a bug.
