### ISSUE TITLE
tournament select requires participants to be >1

### ISSUE THREAD

**Issue by hongxuchen** [m-decoster/RsGenetic#27]
https://github.com/m-decoster/RsGenetic/blob/master/src/sim/select/tournament.rs#L63-L71

For tournament selection, line 70 requires that at least there are 2 elements; when 1 participant is specified in user code, it will cause index out of bound panic.

**Comment by m-decoster** [comment]
Thanks for letting me know. I will push a hotfix later tonight.

**Comment by m-decoster** [comment]
Fixed in 969343dd (available on crates.io as version 1.7.11).
