### ISSUE TITLE
Non-consuming SimulatorBuilder pattern

### ISSUE THREAD

**Issue by hongxuchen** [m-decoster/RsGenetic#28]
The current `SimulatorBuilder` is implemented in a *consuming builder pattern*. According to https://aturon.github.io/ownership/builders.html the preferred is the non-consuming one.

IMO the non-consuming pattern may be better here:
- `set_*` functions implies it is mutable and does not return *new* instance.
- sometimes I need to separate different `set_*` however assigning to a new builder requires more word typings.

**Comment by m-decoster** [comment]
This issue has been fixed in c7b09a5, version 1.8.0. You can now use the builder functions starting with `with_` instead of `set_`.
